name: Publish Package

on:
  release:
    types: [created]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install packages
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_INSTALL_PA_TOKEN }}

      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/

      - name: Install npm 9.2.0
        run: npm i -g npm@9.2.0

      - name: Install packages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_INSTALL_PA_TOKEN }}
        run: npm ci

      - run: npm publish